import "oaidl.idl";
import "ocidl.idl";

[
	object,
	local,
	uuid(4EB60872-ABE8-4BCE-810B-E8B7DAEB8C0F),
	pointer_default(unique)
]
interface ISwitchType : IUnknown
{
}

typedef [v1_enum] enum
{
	ENGINE_CAPABILITY_DEFAULT	= 0x00000000,
	ENGINE_CAPABILITY_CONFIG	= 0x00000001
} ENGINE_CAPABILITIES;

[
	object,
	local,
	uuid(F90DC01C-72F4-400F-8428-5A0F77548578),
	pointer_default(unique)
]
interface ISwitchEngine : IUnknown
{
	HRESULT Config([in] HWND switcher);
	HRESULT GetCapabilities([out, retval] ENGINE_CAPABILITIES *result);
	HRESULT LoadSwitchType([in, string] LPCWSTR switchDirectory, [out, retval] ISwitchType **result);
};
